import { defineConfig, devices } from "@playwright/test";

const PORT = Number(process.env.PORT ?? 3000);
const baseURL = process.env.PLAYWRIGHT_BASE_URL ?? `http://localhost:${PORT}`;

/**
 * E2E + accessibility + visual checks at the two viewports the brief mandates (390 px, 1440 px).
 * Runs against a production build so CSP behaves as in deployment.
 */
export default defineConfig({
  testDir: "tests/e2e",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: process.env.CI ? [["github"], ["html", { open: "never" }]] : [["list"]],
  // Visual baselines are Linux-only (font rendering differs per OS); they are generated by CI and committed.
  // Local runs on macOS/Windows still execute every functional and accessibility assertion.
  snapshotPathTemplate: "{testDir}/__screenshots__/{testFileName}/{arg}-{projectName}-{platform}{ext}",
  ignoreSnapshots: process.platform !== "linux",
  expect: { toHaveScreenshot: { maxDiffPixelRatio: 0.02 } },
  use: {
    baseURL,
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [
    {
      name: "mobile",
      // Chromium everywhere (CI installs only Chromium); iPhone metrics keep touch + DPR realistic.
      use: { ...devices["iPhone 14"], browserName: "chromium", viewport: { width: 390, height: 844 }, isMobile: true },
    },
    {
      name: "desktop",
      use: { ...devices["Desktop Chrome"], viewport: { width: 1440, height: 900 } },
    },
  ],
  webServer: {
    command: process.env.PLAYWRIGHT_DEV ? "pnpm dev" : "pnpm start",
    url: `${baseURL}/api/health`,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
});
